client_build:
  before_script:
    - cd ./client

  stage: build
  image: node:latest
  script:
    - npm install
    # - npm run build
  cache:
    key: 
      files:
        - client/package.json
    paths:
      - client/node_modules/
  only:
    changes:
      - "client/*"

client_test:
  before_script:
    - cd ./client

  stage: test
  image: node:latest
  script:
    - CI=true npm test
  cache:
    key: 
      files:
        - client/package.json
    paths:
      - client/node_modules/
  only:
    changes:
      - "client/*"