server_build:
  before_script:
    - cd ./server

  image: python:latest
  stage: build
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  cache:
    key: 
      files:
        - server/requirements.txt
    paths:
      - server/venv/
      - .cache/pip
  only:
    changes:
      - "server/**/*"

server_test:
  before_script:
    - cd ./server
    - source venv/bin/activate

  image: python:latest
  stage: test
  script:
    - pytest
  cache:
    key: 
      files:
        - server/requirements.txt
    paths:
      - server/venv/
      - .cache/pip
  only:
    changes:
      - "server/**/*"
