stages:
  - test
  
server_test:
  before_script:
    - cd ./server
    - echo "Installing prerequisites..."
    - pip install -r requirements.txt
  stage: test
  image: python:latest
  script:
    - echo "Running tests..."
    - pytest
    - echo "Success!"