"""empty message

<<<<<<< HEAD:server/migrations/versions/2abd18d3b451_.py
Revision ID: 2abd18d3b451
Revises: 
Create Date: 2021-02-02 10:25:21.123639
=======
Revision ID: 066b79f9b83b
Revises: 
Create Date: 2021-02-03 17:20:38.272813
>>>>>>> A1-105-Bio-feature:server/migrations/versions/066b79f9b83b_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:server/migrations/versions/2abd18d3b451_.py
revision = '2abd18d3b451'
=======
revision = '066b79f9b83b'
>>>>>>> A1-105-Bio-feature:server/migrations/versions/066b79f9b83b_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('default_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('bio', sa.String(length=140), nullable=True),
    sa.Column('private_account', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('post',
    sa.Column('id', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('author_id', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('created', sa.BigInteger(), nullable=True),
    sa.Column('modified', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.String(length=1000), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.Column('host', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('community_id', sa.String(length=1000), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'community_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('community')
    # ### end Alembic commands ###
