"""empty message

<<<<<<< Updated upstream:server/migrations/versions/6154cebbe233_.py
Revision ID: 6154cebbe233
Revises: 
Create Date: 2021-01-22 15:09:18.301398
=======
Revision ID: 3388d3d7f41e
Revises: 
Create Date: 2021-01-26 15:02:29.403232
>>>>>>> Stashed changes:server/migrations/versions/3388d3d7f41e_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< Updated upstream:server/migrations/versions/6154cebbe233_.py
revision = '6154cebbe233'
=======
revision = '3388d3d7f41e'
>>>>>>> Stashed changes:server/migrations/versions/3388d3d7f41e_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('default_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('community_administrators',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('community_contributors',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('community_guests',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('community_members',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('community_prohibited',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('author_id', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('created', sa.BigInteger(), nullable=True),
    sa.Column('modified', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.String(length=1000), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('community_prohibited')
    op.drop_table('community_members')
    op.drop_table('community_guests')
    op.drop_table('community_contributors')
    op.drop_table('community_administrators')
    op.drop_table('user')
    op.drop_table('community')
    # ### end Alembic commands ###
