"""empty message

Revision ID: 3528058f9317
Revises: da84c624b40c
Create Date: 2021-01-21 11:41:45.755795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3528058f9317'
down_revision = 'da84c624b40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_guests',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_guests')
    # ### end Alembic commands ###
