"""empty message

Revision ID: 3e6395bb8b96
Revises: 
Create Date: 2021-01-26 10:52:17.300070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6395bb8b96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('bio', sa.String(length=140), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('administrating',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('author_id', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('created', sa.BigInteger(), nullable=True),
    sa.Column('modified', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.String(length=1000), nullable=True),
    sa.Column('community_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('administrating')
    op.drop_table('user')
    op.drop_table('community')
    # ### end Alembic commands ###
